// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client"

/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = []
/** @type { import('../../client/src').ClientConstructor<{}> } */
const DatabaseClient = buildClient()
const defaultOptions = {
  databaseURL:
    "https://Remco-s-workspace-jq8rds.eu-central-1.xata.sh/db/remcostoeten-portfolio-IDE",
}
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables)
    this.db = undefined
  }
}
let instance = undefined
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance
  instance = new XataClient()
  return instance
}
